// Auto-generated by backend/src/scripts/upload-frontend-images-to-cloudinary.js
// Do not edit manually. Re-run the script to update.

export const industryImages = {
  "agri-fmcg-beverage-pp": {
    name: "Agri&fmcg-beverage-pp",
    images: [
      { file: "image40.jpeg", url: "https://res.cloudinary.com/docyipoze/image/upload/v1756806258/cbm/industries/agri-fmcg-beverage-pp/gqgaqozpioawuhxmivcy.jpg", publicId: "cbm/industries/agri-fmcg-beverage-pp/gqgaqozpioawuhxmivcy" },
      { file: "image39.jpeg", url: "https://res.cloudinary.com/docyipoze/image/upload/v1756806260/cbm/industries/agri-fmcg-beverage-pp/pjpje3wuqlgee8selagi.jpg", publicId: "cbm/industries/agri-fmcg-beverage-pp/pjpje3wuqlgee8selagi" },
    ]
  },
  "cement-plants": {
    name: "Cement Plants",
    images: [
      { file: "image20.jpeg", url: "https://res.cloudinary.com/docyipoze/image/upload/v1756806261/cbm/industries/cement-plants/hi6mpuj7egh6x74j88ka.jpg", publicId: "cbm/industries/cement-plants/hi6mpuj7egh6x74j88ka" },
      { file: "image19.png", url: "https://res.cloudinary.com/docyipoze/image/upload/v1756806267/cbm/industries/cement-plants/gqlj3go1zzshvbogghcf.jpg", publicId: "cbm/industries/cement-plants/gqlj3go1zzshvbogghcf" },
    ]
  },
  "fertilizer-plants": {
    name: "Fertilizer Plants",
    images: [
      { file: "image28.jpeg", url: "https://res.cloudinary.com/docyipoze/image/upload/v1756806269/cbm/industries/fertilizer-plants/zsox7hqhnxpe4jwczvnt.jpg", publicId: "cbm/industries/fertilizer-plants/zsox7hqhnxpe4jwczvnt" },
      { file: "image27.jpeg", url: "https://res.cloudinary.com/docyipoze/image/upload/v1756806272/cbm/industries/fertilizer-plants/d98lxpgtqsnkwjtufnkq.jpg", publicId: "cbm/industries/fertilizer-plants/d98lxpgtqsnkwjtufnkq" },
    ]
  },
  "fso-fpso": {
    name: "FSO-FPSO",
    images: [
      { file: "image32.jpeg", url: "https://res.cloudinary.com/docyipoze/image/upload/v1756806273/cbm/industries/fso-fpso/qmbnidojair3anpjvkxw.jpg", publicId: "cbm/industries/fso-fpso/qmbnidojair3anpjvkxw" },
      { file: "image31.png", url: "https://res.cloudinary.com/docyipoze/image/upload/v1756806276/cbm/industries/fso-fpso/e4aj5mlwuf4xhnme1hhl.jpg", publicId: "cbm/industries/fso-fpso/e4aj5mlwuf4xhnme1hhl" },
    ]
  },
  "heavy-automotive": {
    name: "Heavy Automotive",
    images: [
      { file: "image44.png", url: "https://res.cloudinary.com/docyipoze/image/upload/v1756806278/cbm/industries/heavy-automotive/reod98a2nt4ymwrubs1i.jpg", publicId: "cbm/industries/heavy-automotive/reod98a2nt4ymwrubs1i" },
      { file: "image43.jpeg", url: "https://res.cloudinary.com/docyipoze/image/upload/v1756806279/cbm/industries/heavy-automotive/biim27jwt1l7u1sd3vlg.jpg", publicId: "cbm/industries/heavy-automotive/biim27jwt1l7u1sd3vlg" },
    ]
  },
  "industrial-manufacturing-processing": {
    name: "Industrial Manufacturing & Processing",
    images: [
      { file: "image42.jpeg", url: "https://res.cloudinary.com/docyipoze/image/upload/v1756806282/cbm/industries/industrial-manufacturing-processing/t1ymkvpv0eusgtim5nxx.jpg", publicId: "cbm/industries/industrial-manufacturing-processing/t1ymkvpv0eusgtim5nxx" },
      { file: "image41.jpeg", url: "https://res.cloudinary.com/docyipoze/image/upload/v1756806283/cbm/industries/industrial-manufacturing-processing/tsa0ucda6jezxste2nsz.jpg", publicId: "cbm/industries/industrial-manufacturing-processing/tsa0ucda6jezxste2nsz" },
    ]
  },
  "mining-metals-plants-refineries": {
    name: "Mining & Metals Plants & Refineries",
    images: [
      { file: "image18.jpeg", url: "https://res.cloudinary.com/docyipoze/image/upload/v1756806285/cbm/industries/mining-metals-plants-refineries/vcba4hypoyw0vxdl2ek9.jpg", publicId: "cbm/industries/mining-metals-plants-refineries/vcba4hypoyw0vxdl2ek9" },
      { file: "image17.jpeg", url: "https://res.cloudinary.com/docyipoze/image/upload/v1756806286/cbm/industries/mining-metals-plants-refineries/z67flz0qw2a7u6vdh7kl.jpg", publicId: "cbm/industries/mining-metals-plants-refineries/z67flz0qw2a7u6vdh7kl" },
    ]
  },
  "oil-gas": {
    name: "Oil & Gas",
    images: [
      { file: "image24.jpeg", url: "https://res.cloudinary.com/docyipoze/image/upload/v1756806287/cbm/industries/oil-gas/ltwj3255n2eobaaundpa.jpg", publicId: "cbm/industries/oil-gas/ltwj3255n2eobaaundpa" },
      { file: "image23.jpeg", url: "https://res.cloudinary.com/docyipoze/image/upload/v1756806289/cbm/industries/oil-gas/zh9xmyfzcwq3arihfkpz.jpg", publicId: "cbm/industries/oil-gas/zh9xmyfzcwq3arihfkpz" },
    ]
  },
  "paper-pulp-man-plants": {
    name: "paper&pulp-man-plants",
    images: [
      { file: "image38.jpeg", url: "https://res.cloudinary.com/docyipoze/image/upload/v1756806290/cbm/industries/paper-pulp-man-plants/nttmttuuqmnuo2kpwih7.jpg", publicId: "cbm/industries/paper-pulp-man-plants/nttmttuuqmnuo2kpwih7" },
      { file: "image37.jpeg", url: "https://res.cloudinary.com/docyipoze/image/upload/v1756806292/cbm/industries/paper-pulp-man-plants/s9czwhwykxxbijsldvlg.jpg", publicId: "cbm/industries/paper-pulp-man-plants/s9czwhwykxxbijsldvlg" },
    ]
  },
  "petrochemicals-p-r": {
    name: "petrochemicals-p-r",
    images: [
      { file: "image26.jpeg", url: "https://res.cloudinary.com/docyipoze/image/upload/v1756806294/cbm/industries/petrochemicals-p-r/apt0rvrtlpwuahj7h3ny.jpg", publicId: "cbm/industries/petrochemicals-p-r/apt0rvrtlpwuahj7h3ny" },
      { file: "image25.jpeg", url: "https://res.cloudinary.com/docyipoze/image/upload/v1756806295/cbm/industries/petrochemicals-p-r/vaamwjvttbwdaofgs0g5.jpg", publicId: "cbm/industries/petrochemicals-p-r/vaamwjvttbwdaofgs0g5" },
    ]
  },
  "pharmaceutical-plants": {
    name: "pharmaceutical-plants",
    images: [
      { file: "image30.jpeg", url: "https://res.cloudinary.com/docyipoze/image/upload/v1756806297/cbm/industries/pharmaceutical-plants/wjyf4ujxsft1zcsz5hb6.jpg", publicId: "cbm/industries/pharmaceutical-plants/wjyf4ujxsft1zcsz5hb6" },
      { file: "image29.jpeg", url: "https://res.cloudinary.com/docyipoze/image/upload/v1756806298/cbm/industries/pharmaceutical-plants/cvkyx6e8xyimv1olgci4.jpg", publicId: "cbm/industries/pharmaceutical-plants/cvkyx6e8xyimv1olgci4" },
    ]
  },
  "power-plants-utilities": {
    name: "power-plants-utilities",
    images: [
      { file: "image34.jpeg", url: "https://res.cloudinary.com/docyipoze/image/upload/v1756806300/cbm/industries/power-plants-utilities/chhxxywucn24owkzzike.jpg", publicId: "cbm/industries/power-plants-utilities/chhxxywucn24owkzzike" },
      { file: "image33.jpeg", url: "https://res.cloudinary.com/docyipoze/image/upload/v1756806303/cbm/industries/power-plants-utilities/xauxupcp5snobub0knn7.jpg", publicId: "cbm/industries/power-plants-utilities/xauxupcp5snobub0knn7" },
    ]
  },
  "railways": {
    name: "railways",
    images: [
      { file: "image46.jpeg", url: "https://res.cloudinary.com/docyipoze/image/upload/v1756806305/cbm/industries/railways/y5effkf3tiqyoi7i4t4t.jpg", publicId: "cbm/industries/railways/y5effkf3tiqyoi7i4t4t" },
      { file: "image45.jpeg", url: "https://res.cloudinary.com/docyipoze/image/upload/v1756806307/cbm/industries/railways/dtmqkyqqyxyxjnrz87tw.jpg", publicId: "cbm/industries/railways/dtmqkyqqyxyxjnrz87tw" },
    ]
  },
  "roads-and-bridges": {
    name: "Roads and Bridges",
    images: [
      { file: "image48.jpeg", url: "https://res.cloudinary.com/docyipoze/image/upload/v1756806309/cbm/industries/roads-and-bridges/ekyfjdazclkffckjfj1b.jpg", publicId: "cbm/industries/roads-and-bridges/ekyfjdazclkffckjfj1b" },
      { file: "image47.jpeg", url: "https://res.cloudinary.com/docyipoze/image/upload/v1756806310/cbm/industries/roads-and-bridges/iduaihsb1nboubrunqdv.jpg", publicId: "cbm/industries/roads-and-bridges/iduaihsb1nboubrunqdv" },
    ]
  },
  "steelplants": {
    name: "steelplants",
    images: [
      { file: "image22.jpeg", url: "https://res.cloudinary.com/docyipoze/image/upload/v1756806311/cbm/industries/steelplants/z1mkjachceuoqvjiooaf.jpg", publicId: "cbm/industries/steelplants/z1mkjachceuoqvjiooaf" },
      { file: "image21.jpeg", url: "https://res.cloudinary.com/docyipoze/image/upload/v1756806312/cbm/industries/steelplants/oaqecwxm189dfp1z5vzu.jpg", publicId: "cbm/industries/steelplants/oaqecwxm189dfp1z5vzu" },
    ]
  },
  "sugarplants": {
    name: "sugarplants",
    images: [
      { file: "image36.jpeg", url: "https://res.cloudinary.com/docyipoze/image/upload/v1756806313/cbm/industries/sugarplants/woncvgnzqvxpqtw5q74u.jpg", publicId: "cbm/industries/sugarplants/woncvgnzqvxpqtw5q74u" },
      { file: "image35.jpeg", url: "https://res.cloudinary.com/docyipoze/image/upload/v1756806315/cbm/industries/sugarplants/gks7yyjocmgqy3migivq.jpg", publicId: "cbm/industries/sugarplants/gks7yyjocmgqy3migivq" },
    ]
  },
};

export default industryImages;
